name: test

on: [push]

jobs:
  build:
    env: 
    abc:1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: a

        run: |
          echo ${abc}
          export A=1
